### ISSUE TITLE
Is axios mandatory?

### ISSUE THREAD

**Issue by francescjimenez** [EkoLabs/eko-js-sdk#5]
On the last version 0.5, I see that you are using Axios for only one request, to do a GET. This increase the size of the library x2

https://bundlephobia.com/result?p=eko-js-sdk@0.0.5

**Comment by Melatonin64** [comment]
Thanks @francescjimenez !
We'll re-evaluate the use of axios and keep you posted.

**Comment by DivyaMahadevan** [comment]
Hey @francescjimenez !
Just wanted to let you know that axios was removed in the latest version (0.0.6)
