### ISSUE TITLE
Possible loading slowdown on Android devices

### ISSUE THREAD

**Issue by cybrwlf525** [EkoLabs/eko-js-sdk#6]
Two of my co-workers who have android devices opened the same Eko project through the direct embed URL and then the embedded via SDK version on their phones. The Eko project loaded around 5 seconds or less on the direct URL and took 20+ seconds on the SDK embed version. Wanted to flag as a possible issue/inefficiency since it was being embedded thru the SDK.

**Comment by cybrwlf525** [comment]
I did not experience this inefficiency on my iOS device, but not sure if it's an isolated issue.

**Comment by Melatonin64** [comment]
Thanks for reporting @cybrwlf525 .
Would you be able to provide a URL where we can reproduce the Android loading issue?

**Comment by cybrwlf525** [comment]
reproduction link: https://www.betterwayhealth.com/pages/beta-glucan-greenmedinfo

**Comment by Melatonin64** [comment]
Thank you @cybrwlf525 !
Reproduced on an Android device.
It looks like the parent page is very large and includes lots of video elements - I believe what might be happening here is that the Android browser might be prioritizing the load of elements on the parent frame over the iframe.

Are you able to reproduce this issue on a simpler parent page?

**Comment by cybrwlf525** [comment]
Hey there, currently do not have a setup for replicating on a simpler parent page, so for now we can close this issue, I will test on a simpler page for future implementations to rule out the sdk causing the slow loading issue.
